export const GET_ALL_POKEMON = "GET_ALL_POKEMON";
export const GET_NAME_POKEMON = "GET_NAME_POKEMON";
export const FILTER_TYPES = "FILTER_TYPES"
export const FILTER_FUENTE = "FILTER_FUENTE"
export const ORDEN_ATTACK = "ORDEN_ATTACK"
export const ORDEN_ALFABETICO = "ORDEN_ALFABETICO"
export const CREATE_POKEMON = "CREATE_POKEMON"
export const RESET = "RESET"

//PAGINADO
export const PAGINATE = "PAGINATE"
